version: "3.8"

services:
  postgres_container:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    build: .
    container_name: fastapi_container
    restart: always
    depends_on:
      - postgres_container
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_container:5432/body_performance
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
